// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: 'cours'}],
  tutoriels: [{type: 'autogenerated', dirName: 'tutoriels'}],
  tp: [{type: 'autogenerated', dirName: 'tp'}],
};

module.exports = sidebars;
